---
- name: show version and other user level commands
  hosts: CSR-Router
  gather_facts: false
  connection: local

  tasks:
    - name: Override device configuration of all interfaces with provided configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet2
          ipv4: 
          - address: 192.168.0.1/24
          
 
      


